title: WFinance
description: Seu controle financeiro, do seu jeito.
url: https://wrodriguesjr.github.io
baseurl: /WFinanceDocs
lang: pt-BR
timezone: America/Sao_Paulo

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-seo-tag

optional_front_matter:
  enabled: true

relative_links:
  enabled: true
  collections: true

titles_from_headings:
  enabled: true
  strip_title: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
      image: /assets/images/hero.png
  - scope:
      path: "index.html"
    values:
      layout: home
